[package]
name = "raw_processor"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
android_logger = "0.15.1"
jni = "0.21.1"
log = "0.4.27"
vulkano = "0.35.1"
vulkano-shaders = "0.35.0"
